### PR TITLE
Reduce input required for quick version update

### PR DESCRIPTION
**Pull request by Trenly**
@vedantmgoyal2009 @OfficialEsco

### CODE REVIEW

**Comment by OfficialEsco** [comment]
👌
```
Installer Entry #1:

        InstallerLocale: en-US
        Architecture: x64
        InstallerType: msi
        Scope: machine


```

**Comment by OfficialEsco** [comment]
Hold up, hold up, hold up, bug alert 🚨🚨🚨
`ProductCode: ""` is currently getting in the manifest if you press enter

**Comment by Trenly** [comment]
> Hold up, hold up, hold up, bug alert 🚨🚨🚨
> `ProductCode: ""` is currently getting in the manifest if you press enter

Try now

**Comment by OfficialEsco** [comment]
Nope https://github.com/microsoft/winget-pkgs/pull/27951/files

**Comment by Trenly** [comment]
> Nope [OfficialEsco@d35ab4f](https://github.com/OfficialEsco/winget-pkgs/commit/d35ab4f214fe9a3386f72d1a54555e20606aa198)


Ahhhh I see the issue there; 1 sec and I'll have another commit

**Comment by OfficialEsco** [comment]
That did it 👌

**Review by vedantmgoyal2009 — APPROVED** [review]

**Pull request merged**
